# Generated by cucumber-sinatra. (2013-11-09 14:35:08 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = chitter

class chitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  chitterWorld.new
end
